const commandCategories = {

    // =========================================================
    // 1. SYSTEM INFORMATION - 50
    // =========================================================
    systemInfo: [
        {name:"System Information",command:"systeminfo",description:"Complete Windows system information"},
        {name:"Hostname",command:"hostname",description:"Shows computer hostname"},
        {name:"Windows Version",command:"winver",description:"Shows Windows version"},
        {name:"Current User",command:"whoami",description:"Shows current user"},
        {name:"Logged Users",command:"query user",description:"Shows logged-in users"},
        {name:"OS Caption",command:"wmic os get Caption",description:"Shows Windows edition"},
        {name:"OS Version",command:"wmic os get Version",description:"Shows Windows version"},
        {name:"OS Build",command:"wmic os get BuildNumber",description:"Shows Windows build"},
        {name:"Architecture",command:"wmic os get OSArchitecture",description:"Shows 32/64-bit architecture"},
        {name:"Computer Model",command:"wmic computersystem get model",description:"Shows computer model"},
        {name:"Manufacturer",command:"wmic computersystem get manufacturer",description:"Shows manufacturer"},
        {name:"Serial Number",command:"wmic bios get serialnumber",description:"Shows BIOS serial number"},
        {name:"BIOS Version",command:"wmic bios get smbiosbiosversion",description:"Shows BIOS version"},
        {name:"CPU Name",command:"wmic cpu get name",description:"Shows processor name"},
        {name:"CPU Cores",command:"wmic cpu get NumberOfCores",description:"Shows CPU cores"},
        {name:"CPU Threads",command:"wmic cpu get NumberOfLogicalProcessors",description:"Shows logical processors"},
        {name:"CPU Speed",command:"wmic cpu get MaxClockSpeed",description:"Shows CPU clock speed"},
        {name:"RAM",command:"wmic computersystem get TotalPhysicalMemory",description:"Shows installed RAM"},
        {name:"RAM Modules",command:"wmic memorychip get capacity",description:"Shows RAM module capacity"},
        {name:"RAM Speed",command:"wmic memorychip get speed",description:"Shows RAM speed"},
        {name:"Disk Model",command:"wmic diskdrive get model",description:"Shows disk model"},
        {name:"Disk Size",command:"wmic diskdrive get size",description:"Shows disk size"},
        {name:"Disk Status",command:"wmic diskdrive get status",description:"Shows disk status"},
        {name:"BIOS Manufacturer",command:"wmic bios get manufacturer",description:"Shows BIOS manufacturer"},
        {name:"BIOS Serial",command:"wmic bios get serialnumber",description:"Shows BIOS serial"},
        {name:"Last Boot",command:"wmic os get lastbootuptime",description:"Shows last boot time"},
        {name:"Windows Directory",command:"echo %windir%",description:"Shows Windows directory"},
        {name:"System Drive",command:"echo %SystemDrive%",description:"Shows system drive"},
        {name:"Program Files",command:"echo %ProgramFiles%",description:"Shows Program Files path"},
        {name:"Temp Path",command:"echo %TEMP%",description:"Shows temporary folder"},
        {name:"Username",command:"echo %USERNAME%",description:"Shows username"},
        {name:"Computer Name",command:"echo %COMPUTERNAME%",description:"Shows computer name"},
        {name:"Domain",command:"echo %USERDOMAIN%",description:"Shows user domain"},
        {name:"Logon Server",command:"echo %LOGONSERVER%",description:"Shows logon server"},
        {name:"Time Zone",command:"tzutil /g",description:"Shows time zone"},
        {name:"Date",command:"date /t",description:"Shows system date"},
        {name:"Time",command:"time /t",description:"Shows system time"},
        {name:"Environment Variables",command:"set",description:"Shows environment variables"},
        {name:"Windows Activation",command:"slmgr /xpr",description:"Checks Windows activation"},
        {name:"Windows License",command:"slmgr /dlv",description:"Shows detailed license information"},
        {name:"System Properties",command:"sysdm.cpl",description:"Opens System Properties"},
        {name:"Device Manager",command:"devmgmt.msc",description:"Opens Device Manager"},
        {name:"Computer Management",command:"compmgmt.msc",description:"Opens Computer Management"},
        {name:"System Configuration",command:"msconfig",description:"Opens System Configuration"},
        {name:"Task Manager",command:"taskmgr",description:"Opens Task Manager"},
        {name:"Resource Monitor",command:"resmon",description:"Opens Resource Monitor"},
        {name:"Performance Monitor",command:"perfmon",description:"Opens Performance Monitor"},
        {name:"System Information GUI",command:"msinfo32",description:"Opens System Information"},
        {name:"DirectX Diagnostic",command:"dxdiag",description:"Opens DirectX diagnostics"},
        {name:"Windows About",command:"ms-settings:about",description:"Opens About settings"}
    ],

    // =========================================================
    // 2. NETWORKING - 50
    // =========================================================
    networking: [
        {name:"IP Configuration",command:"ipconfig",description:"Shows IP configuration"},
        {name:"Detailed IP",command:"ipconfig /all",description:"Shows detailed IP information"},
        {name:"Release IP",command:"ipconfig /release",description:"Releases DHCP address"},
        {name:"Renew IP",command:"ipconfig /renew",description:"Renews DHCP address"},
        {name:"Flush DNS",command:"ipconfig /flushdns",description:"Clears DNS cache"},
        {name:"Display DNS",command:"ipconfig /displaydns",description:"Displays DNS cache"},
        {name:"Register DNS",command:"ipconfig /registerdns",description:"Registers DNS records"},
        {name:"Ping Gateway",command:"ping 192.168.1.1",description:"Tests gateway connectivity"},
        {name:"Ping Google",command:"ping 8.8.8.8",description:"Tests internet connectivity"},
        {name:"Continuous Ping",command:"ping 8.8.8.8 -t",description:"Continuous connectivity test"},
        {name:"Ping Domain",command:"ping google.com",description:"Tests DNS and connectivity"},
        {name:"Trace Route",command:"tracert 8.8.8.8",description:"Traces network path"},
        {name:"DNS Lookup",command:"nslookup google.com",description:"Performs DNS lookup"},
        {name:"Reverse DNS",command:"nslookup 8.8.8.8",description:"Performs reverse DNS lookup"},
        {name:"ARP Table",command:"arp -a",description:"Shows ARP cache"},
        {name:"ARP Delete",command:"arp -d *",description:"Clears ARP entries"},
        {name:"Routing Table",command:"route print",description:"Shows routing table"},
        {name:"Network Connections",command:"netstat -ano",description:"Shows active connections"},
        {name:"Listening Ports",command:"netstat -ano | findstr LISTENING",description:"Shows listening ports"},
        {name:"Established Connections",command:"netstat -ano | findstr ESTABLISHED",description:"Shows established connections"},
        {name:"TCP Statistics",command:"netstat -s -p tcp",description:"Shows TCP statistics"},
        {name:"UDP Statistics",command:"netstat -s -p udp",description:"Shows UDP statistics"},
        {name:"MAC Address",command:"getmac",description:"Shows MAC address"},
        {name:"Detailed MAC",command:"getmac /v",description:"Shows detailed MAC information"},
        {name:"Network Shares",command:"net share",description:"Shows shared folders"},
        {name:"Mapped Drives",command:"net use",description:"Shows mapped drives"},
        {name:"Delete Network Drive",command:"net use * /delete",description:"Removes network mappings"},
        {name:"Network Statistics",command:"netstat -e",description:"Shows Ethernet statistics"},
        {name:"Interface List",command:"netsh interface show interface",description:"Shows network interfaces"},
        {name:"Interface IP",command:"netsh interface ip show config",description:"Shows interface configuration"},
        {name:"WiFi Profiles",command:"netsh wlan show profiles",description:"Shows saved Wi-Fi profiles"},
        {name:"WiFi Details",command:"netsh wlan show interfaces",description:"Shows current Wi-Fi information"},
        {name:"WiFi Drivers",command:"netsh wlan show drivers",description:"Shows Wi-Fi driver details"},
        {name:"WiFi Report",command:"netsh wlan show wlanreport",description:"Creates WLAN report"},
        {name:"Firewall Profiles",command:"netsh advfirewall show allprofiles",description:"Shows firewall profiles"},
        {name:"Firewall State",command:"netsh advfirewall show currentprofile",description:"Shows current firewall profile"},
        {name:"Test Port 443",command:"powershell Test-NetConnection google.com -Port 443",description:"Tests HTTPS port"},
        {name:"Test Port 80",command:"powershell Test-NetConnection google.com -Port 80",description:"Tests HTTP port"},
        {name:"Test Port 3389",command:"powershell Test-NetConnection SERVER -Port 3389",description:"Tests RDP port"},
        {name:"Test Port 445",command:"powershell Test-NetConnection SERVER -Port 445",description:"Tests SMB port"},
        {name:"Test Port 53",command:"powershell Test-NetConnection SERVER -Port 53",description:"Tests DNS port"},
        {name:"DNS Servers",command:"ipconfig /all | findstr DNS",description:"Shows configured DNS servers"},
        {name:"Default Gateway",command:"ipconfig | findstr Gateway",description:"Shows default gateway"},
        {name:"IPv4 Address",command:"ipconfig | findstr IPv4",description:"Shows IPv4 address"},
        {name:"IPv6 Address",command:"ipconfig | findstr IPv6",description:"Shows IPv6 address"},
        {name:"Network Adapter List",command:"wmic nic get Name,NetEnabled",description:"Lists network adapters"},
        {name:"Network Adapter Config",command:"wmic nicconfig get Description,IPAddress,IPEnabled",description:"Shows adapter IP configuration"},
        {name:"SMB Connections",command:"net session",description:"Shows SMB sessions"},
        {name:"DNS Client Service",command:"sc query dnscache",description:"Checks DNS Client service"}
    ],

    // =========================================================
    // 3. USERS & ACCOUNTS - 50
    // =========================================================
    users: [
        {name:"Local Users",command:"net user",description:"Lists local users"},
        {name:"User Details",command:"net user %username%",description:"Shows current user details"},
        {name:"Create User",command:"net user TestUser Password123 /add",description:"Creates local user"},
        {name:"Delete User",command:"net user TestUser /delete",description:"Deletes local user"},
        {name:"Change Password",command:"net user %username% *",description:"Changes user password"},
        {name:"Enable User",command:"net user TestUser /active:yes",description:"Enables user account"},
        {name:"Disable User",command:"net user TestUser /active:no",description:"Disables user account"},
        {name:"Local Groups",command:"net localgroup",description:"Lists local groups"},
        {name:"Administrators",command:"net localgroup administrators",description:"Lists administrators"},
        {name:"Add Admin",command:"net localgroup administrators TestUser /add",description:"Adds user to administrators"},
        {name:"Remove Admin",command:"net localgroup administrators TestUser /delete",description:"Removes user from administrators"},
        {name:"Remote Desktop Users",command:"net localgroup \"Remote Desktop Users\"",description:"Shows RDP users"},
        {name:"Add RDP User",command:"net localgroup \"Remote Desktop Users\" TestUser /add",description:"Adds RDP permission"},
        {name:"Remove RDP User",command:"net localgroup \"Remote Desktop Users\" TestUser /delete",description:"Removes RDP permission"},
        {name:"Password Policy",command:"net accounts",description:"Shows local password policy"},
        {name:"Domain Policy",command:"net accounts /domain",description:"Shows domain password policy"},
        {name:"Current Username",command:"echo %username%",description:"Shows username"},
        {name:"Current User SID",command:"whoami /user",description:"Shows user SID"},
        {name:"User Groups",command:"whoami /groups",description:"Shows group memberships"},
        {name:"User Privileges",command:"whoami /priv",description:"Shows privileges"},
        {name:"User FQDN",command:"whoami /fqdn",description:"Shows user FQDN"},
        {name:"Logged Sessions",command:"query session",description:"Shows terminal sessions"},
        {name:"Remote Sessions",command:"qwinsta",description:"Shows RDP sessions"},
        {name:"Logoff Session",command:"logoff SESSION_ID",description:"Logs off session"},
        {name:"Lock Computer",command:"rundll32.exe user32.dll,LockWorkStation",description:"Locks workstation"},
        {name:"Sign Out",command:"shutdown /l",description:"Signs out current user"},
        {name:"Switch User",command:"tsdiscon",description:"Disconnects current session"},
        {name:"Domain User",command:"whoami /upn",description:"Shows user principal name"},
        {name:"Domain",command:"echo %USERDOMAIN%",description:"Shows user domain"},
        {name:"Logon Server",command:"echo %LOGONSERVER%",description:"Shows logon server"},
        {name:"User Environment",command:"set USER",description:"Shows user environment variables"},
        {name:"Credential Manager",command:"control /name Microsoft.CredentialManager",description:"Opens Credential Manager"},
        {name:"User Accounts GUI",command:"netplwiz",description:"Opens User Accounts"},
        {name:"Advanced User Accounts",command:"control userpasswords2",description:"Opens advanced user settings"},
        {name:"Computer Users MMC",command:"lusrmgr.msc",description:"Opens Local Users and Groups"},
        {name:"Account Lockout Check",command:"net user TestUser",description:"Checks account status"},
        {name:"Account Expiry",command:"net user TestUser | findstr /I expires",description:"Checks account expiry"},
        {name:"Password Last Set",command:"net user TestUser | findstr /I \"Password last set\"",description:"Checks password date"},
        {name:"Password Required",command:"net user TestUser | findstr /I \"Password required\"",description:"Checks password requirement"},
        {name:"Workstation Logon",command:"net user TestUser | findstr /I \"Workstations allowed\"",description:"Checks allowed workstations"},
        {name:"User Comment",command:"net user TestUser | findstr /I \"Comment\"",description:"Shows user comment"},
        {name:"User Profile",command:"echo %USERPROFILE%",description:"Shows user profile path"},
        {name:"AppData",command:"echo %APPDATA%",description:"Shows AppData path"},
        {name:"Local AppData",command:"echo %LOCALAPPDATA%",description:"Shows Local AppData"},
        {name:"Public Profile",command:"echo %PUBLIC%",description:"Shows Public profile"},
        {name:"Temp User Folder",command:"echo %TEMP%",description:"Shows user temp path"},
        {name:"Run As User",command:"runas /user:DOMAIN\\USERNAME cmd",description:"Runs application as another user"},
        {name:"Who Am I",command:"whoami",description:"Shows current identity"},
        {name:"Token Information",command:"whoami /all",description:"Shows complete security token"}
    ],

    // =========================================================
    // 4. SERVICES & PROCESSES - 50
    // =========================================================
    services: [
        {name:"All Services",command:"sc query",description:"Lists Windows services"},
        {name:"Running Services",command:"sc query | findstr RUNNING",description:"Lists running services"},
        {name:"Stopped Services",command:"sc query | findstr STOPPED",description:"Lists stopped services"},
        {name:"Spooler Status",command:"sc query Spooler",description:"Checks Print Spooler"},
        {name:"DNS Client Status",command:"sc query dnscache",description:"Checks DNS Client"},
        {name:"DHCP Client Status",command:"sc query Dhcp",description:"Checks DHCP Client"},
        {name:"Windows Update Status",command:"sc query wuauserv",description:"Checks Windows Update"},
        {name:"BITS Status",command:"sc query bits",description:"Checks BITS"},
        {name:"Start Spooler",command:"net start Spooler",description:"Starts Print Spooler"},
        {name:"Stop Spooler",command:"net stop Spooler",description:"Stops Print Spooler"},
        {name:"Restart Spooler",command:"net stop Spooler && net start Spooler",description:"Restarts Print Spooler"},
        {name:"Start Windows Update",command:"net start wuauserv",description:"Starts Windows Update"},
        {name:"Stop Windows Update",command:"net stop wuauserv",description:"Stops Windows Update"},
        {name:"Start BITS",command:"net start bits",description:"Starts BITS"},
        {name:"Stop BITS",command:"net stop bits",description:"Stops BITS"},
        {name:"Service Configuration",command:"sc qc Spooler",description:"Shows service configuration"},
        {name:"Create Service",command:"sc create TestService binPath= C:\\Test\\test.exe",description:"Creates a Windows service"},
        {name:"Delete Service",command:"sc delete TestService",description:"Deletes a Windows service"},
        {name:"Disable Service",command:"sc config TestService start= disabled",description:"Disables service startup"},
        {name:"Automatic Service",command:"sc config TestService start= auto",description:"Sets automatic startup"},
        {name:"Manual Service",command:"sc config TestService start= demand",description:"Sets manual startup"},
        {name:"Task List",command:"tasklist",description:"Lists running processes"},
        {name:"Detailed Tasks",command:"tasklist /v",description:"Shows detailed processes"},
        {name:"Services by Process",command:"tasklist /svc",description:"Shows services mapped to processes"},
        {name:"Find Process",command:"tasklist | findstr chrome",description:"Searches for process"},
        {name:"Kill Process",command:"taskkill /PID 1234 /F",description:"Terminates process by PID"},
        {name:"Kill Image",command:"taskkill /IM notepad.exe /F",description:"Terminates process by name"},
        {name:"Start Program",command:"start notepad.exe",description:"Starts application"},
        {name:"Task Manager",command:"taskmgr",description:"Opens Task Manager"},
        {name:"Services Console",command:"services.msc",description:"Opens Services console"},
        {name:"Task Scheduler",command:"taskschd.msc",description:"Opens Task Scheduler"},
        {name:"Event Viewer",command:"eventvwr.msc",description:"Opens Event Viewer"},
        {name:"Performance Monitor",command:"perfmon",description:"Opens Performance Monitor"},
        {name:"Resource Monitor",command:"resmon",description:"Opens Resource Monitor"},
        {name:"System Configuration",command:"msconfig",description:"Opens System Configuration"},
        {name:"Scheduled Tasks",command:"schtasks /query",description:"Lists scheduled tasks"},
        {name:"Create Scheduled Task",command:"schtasks /create /tn TestTask /tr notepad.exe /sc daily",description:"Creates scheduled task"},
        {name:"Delete Scheduled Task",command:"schtasks /delete /tn TestTask /f",description:"Deletes scheduled task"},
        {name:"Run Scheduled Task",command:"schtasks /run /tn TestTask",description:"Runs scheduled task"},
        {name:"Stop Scheduled Task",command:"schtasks /end /tn TestTask",description:"Stops scheduled task"},
        {name:"Task Details",command:"schtasks /query /fo LIST /v",description:"Shows detailed task information"},
        {name:"Process Tree",command:"wmic process get Name,ProcessId,ParentProcessId",description:"Shows process hierarchy information"},
        {name:"Process Command Line",command:"wmic process get Name,CommandLine",description:"Shows process command lines"},
        {name:"Process ID",command:"tasklist /fi \"imagename eq explorer.exe\"",description:"Finds Explorer PID"},
        {name:"Restart Explorer",command:"taskkill /f /im explorer.exe && start explorer.exe",description:"Restarts Windows Explorer"},
        {name:"Print Spooler Dependencies",command:"sc enumdepend Spooler",description:"Shows service dependencies"},
        {name:"Service Failure Config",command:"sc qfailure Spooler",description:"Shows service failure actions"},
        {name:"Service Description",command:"sc qdescription Spooler",description:"Shows service description"},
        {name:"Service SID",command:"sc showsid Spooler",description:"Shows service SID information"}
    ],

    // =========================================================
    // 5. ACTIVE DIRECTORY - 50
    // =========================================================
    activeDirectory: [
        {name:"Domain Controller",command:"nltest /dsgetdc:DOMAIN.LOCAL",description:"Finds domain controller"},
        {name:"Domain Trust",command:"nltest /sc_verify:DOMAIN.LOCAL",description:"Verifies secure channel"},
        {name:"Reset Secure Channel",command:"nltest /sc_reset:DOMAIN.LOCAL",description:"Resets secure channel"},
        {name:"Domain Info",command:"nltest /dsregdns",description:"Registers DNS records"},
        {name:"Group Policy Update",command:"gpupdate /force",description:"Forces Group Policy update"},
        {name:"GP Summary",command:"gpresult /r",description:"Shows applied policies"},
        {name:"GP HTML Report",command:"gpresult /h C:\\Temp\\gpresult.html",description:"Creates GP report"},
        {name:"Computer GP",command:"gpresult /scope computer /r",description:"Shows computer policies"},
        {name:"User GP",command:"gpresult /scope user /r",description:"Shows user policies"},
        {name:"AD Users",command:"dsquery user",description:"Lists AD users"},
        {name:"AD Computers",command:"dsquery computer",description:"Lists AD computers"},
        {name:"AD Groups",command:"dsquery group",description:"Lists AD groups"},
        {name:"Find AD User",command:"dsquery user -name USERNAME",description:"Searches AD user"},
        {name:"Find AD Computer",command:"dsquery computer -name COMPUTERNAME",description:"Searches AD computer"},
        {name:"Find AD Group",command:"dsquery group -name GROUPNAME",description:"Searches AD group"},
        {name:"Domain User Details",command:"net user USERNAME /domain",description:"Shows domain user"},
        {name:"Domain Password Policy",command:"net accounts /domain",description:"Shows domain password policy"},
        {name:"Kerberos Tickets",command:"klist",description:"Shows Kerberos tickets"},
        {name:"Purge Kerberos",command:"klist purge",description:"Clears Kerberos tickets"},
        {name:"Kerberos Sessions",command:"klist sessions",description:"Shows Kerberos sessions"},
        {name:"AD Replication Summary",command:"repadmin /replsummary",description:"Shows replication summary"},
        {name:"Replication Status",command:"repadmin /showrepl",description:"Shows replication status"},
        {name:"Sync AD Replication",command:"repadmin /syncall /AdeP",description:"Forces replication"},
        {name:"Domain Controller Diagnostics",command:"dcdiag",description:"Runs DC diagnostics"},
        {name:"DNS Diagnostics",command:"dcdiag /test:dns",description:"Tests DC DNS"},
        {name:"Advertising Test",command:"dcdiag /test:advertising",description:"Tests DC advertising"},
        {name:"Services Test",command:"dcdiag /test:services",description:"Tests DC services"},
        {name:"NetLogons Test",command:"dcdiag /test:netlogons",description:"Tests Netlogon"},
        {name:"SYSVOL Test",command:"dcdiag /test:sysvolcheck",description:"Tests SYSVOL"},
        {name:"FSMO Roles",command:"netdom query fsmo",description:"Shows FSMO role holders"},
        {name:"Domain Controllers",command:"netdom query dc",description:"Lists domain controllers"},
        {name:"Workstations",command:"netdom query workstation",description:"Lists domain workstations"},
        {name:"Domain Trusts",command:"netdom query trust",description:"Shows domain trusts"},
        {name:"AD Sites",command:"nltest /dclist:DOMAIN.LOCAL",description:"Lists domain controllers"},
        {name:"Logon Server",command:"echo %LOGONSERVER%",description:"Shows current logon DC"},
        {name:"User Domain",command:"echo %USERDOMAIN%",description:"Shows user domain"},
        {name:"Domain Name",command:"echo %USERDNSDOMAIN%",description:"Shows DNS domain"},
        {name:"ADSI Edit",command:"adsiedit.msc",description:"Opens ADSI Edit"},
        {name:"Active Directory Users",command:"dsa.msc",description:"Opens AD Users and Computers"},
        {name:"AD Administrative Center",command:"dsac.exe",description:"Opens AD Administrative Center"},
        {name:"Group Policy Management",command:"gpmc.msc",description:"Opens Group Policy Management"},
        {name:"Active Directory Sites",command:"dssite.msc",description:"Opens AD Sites and Services"},
        {name:"AD Domains and Trusts",command:"domain.msc",description:"Opens Domains and Trusts"},
        {name:"AD Schema",command:"schmmgmt.msc",description:"Opens AD Schema console"},
        {name:"LDAP Port Test",command:"powershell Test-NetConnection DC01 -Port 389",description:"Tests LDAP"},
        {name:"LDAPS Port Test",command:"powershell Test-NetConnection DC01 -Port 636",description:"Tests LDAPS"},
        {name:"Kerberos Port Test",command:"powershell Test-NetConnection DC01 -Port 88",description:"Tests Kerberos"},
        {name:"SMB DC Test",command:"powershell Test-NetConnection DC01 -Port 445",description:"Tests SMB"},
        {name:"Global Catalog Test",command:"powershell Test-NetConnection DC01 -Port 3268",description:"Tests Global Catalog"},
        {name:"Secure LDAP Test",command:"powershell Test-NetConnection DC01 -Port 3269",description:"Tests secure Global Catalog"}
    ],

    // =========================================================
    // 6. DISK & STORAGE - 50
    // =========================================================
    storage: [
        {name:"Disk Space",command:"wmic logicaldisk get caption,freespace,size",description:"Shows disk space"},
        {name:"Drive List",command:"wmic logicaldisk get name",description:"Lists drives"},
        {name:"Disk Management",command:"diskmgmt.msc",description:"Opens Disk Management"},
        {name:"DiskPart",command:"diskpart",description:"Opens DiskPart"},
        {name:"List Disks",command:"diskpart /s listdisk.txt",description:"Runs DiskPart script"},
        {name:"Check Disk",command:"chkdsk C:",description:"Checks filesystem"},
        {name:"Check Disk Repair",command:"chkdsk C: /f",description:"Repairs filesystem errors"},
        {name:"Check Disk Scan",command:"chkdsk C: /scan",description:"Scans filesystem online"},
        {name:"Drive Label",command:"vol C:",description:"Shows volume label"},
        {name:"Volume Information",command:"fsutil volume diskfree C:",description:"Shows volume free space"},
        {name:"Diskpart List Volume",command:"powershell Get-Volume",description:"Lists volumes"},
        {name:"Physical Disks",command:"powershell Get-Disk",description:"Lists physical disks"},
        {name:"Partitions",command:"powershell Get-Partition",description:"Lists partitions"},
        {name:"Logical Disks",command:"powershell Get-CimInstance Win32_LogicalDisk",description:"Shows logical disks"},
        {name:"Disk Health",command:"powershell Get-PhysicalDisk",description:"Shows physical disk health"},
        {name:"SMART Status",command:"wmic diskdrive get status",description:"Shows disk SMART status"},
        {name:"Disk Model",command:"wmic diskdrive get model",description:"Shows disk models"},
        {name:"Disk Serial",command:"wmic diskdrive get serialnumber",description:"Shows disk serial numbers"},
        {name:"Disk Interface",command:"wmic diskdrive get interfacetype",description:"Shows disk interface"},
        {name:"Disk Media Type",command:"wmic diskdrive get mediatype",description:"Shows media type"},
        {name:"System Drive",command:"echo %SystemDrive%",description:"Shows Windows drive"},
        {name:"Temporary Files",command:"%TEMP%",description:"Opens temporary folder"},
        {name:"Windows Temp",command:"C:\\Windows\\Temp",description:"Windows temporary folder"},
        {name:"Recent Files",command:"shell:recent",description:"Opens recent files"},
        {name:"Downloads",command:"shell:downloads",description:"Opens Downloads"},
        {name:"Recycle Bin",command:"shell:RecycleBinFolder",description:"Opens Recycle Bin"},
        {name:"Startup Folder",command:"shell:startup",description:"Opens user startup folder"},
        {name:"Common Startup",command:"shell:common startup",description:"Opens common startup folder"},
        {name:"Disk Cleanup",command:"cleanmgr",description:"Opens Disk Cleanup"},
        {name:"Storage Settings",command:"ms-settings:storagesense",description:"Opens Storage settings"},
        {name:"Optimize Drives",command:"dfrgui",description:"Opens drive optimization"},
        {name:"Defrag Analyze",command:"defrag C: /A",description:"Analyzes drive fragmentation"},
        {name:"Defrag Drive",command:"defrag C: /O",description:"Optimizes drive"},
        {name:"System File Checker",command:"sfc /scannow",description:"Scans Windows system files"},
        {name:"SFC Verify",command:"sfc /verifyonly",description:"Verifies system files"},
        {name:"DISM Check",command:"DISM /Online /Cleanup-Image /CheckHealth",description:"Checks Windows image"},
        {name:"DISM Scan",command:"DISM /Online /Cleanup-Image /ScanHealth",description:"Scans Windows image"},
        {name:"DISM Repair",command:"DISM /Online /Cleanup-Image /RestoreHealth",description:"Repairs Windows image"},
        {name:"Mount ISO",command:"powershell Mount-DiskImage -ImagePath C:\\file.iso",description:"Mounts ISO image"},
        {name:"Dismount ISO",command:"powershell Dismount-DiskImage -ImagePath C:\\file.iso",description:"Unmounts ISO image"},
        {name:"File System",command:"fsutil fsinfo volumeinfo C:",description:"Shows filesystem information"},
        {name:"NTFS Info",command:"fsutil fsinfo ntfsinfo C:",description:"Shows NTFS information"},
        {name:"File Handles",command:"handle.exe",description:"Shows open file handles"},
        {name:"Disk Error Events",command:"wevtutil qe System /q:\"*[System[(Provider[@Name='disk'])]]\" /f:text",description:"Shows disk event errors"},
        {name:"Windows Recovery",command:"systemreset",description:"Opens reset/recovery interface"},
        {name:"Recovery Environment",command:"reagentc /info",description:"Shows Windows Recovery status"},
        {name:"Enable Recovery",command:"reagentc /enable",description:"Enables Windows Recovery"},
        {name:"Disable Recovery",command:"reagentc /disable",description:"Disables Windows Recovery"},
        {name:"Boot Configuration",command:"bcdedit",description:"Shows boot configuration"},
        {name:"BCD Backup",command:"bcdedit /export C:\\BCD_Backup",description:"Exports boot configuration"}
    ],

    // =========================================================
    // 7. PRINTERS - 50
    // =========================================================
    printers: [
        {name:"Printers List",command:"wmic printer get name,status",description:"Lists printers"},
        {name:"Printer Details",command:"wmic printer get name,drivername,portname",description:"Shows printer details"},
        {name:"Default Printer",command:"wmic printer get name,default",description:"Shows default printer"},
        {name:"Printer GUI",command:"control printers",description:"Opens Devices and Printers"},
        {name:"Printer Settings",command:"ms-settings:printers",description:"Opens printer settings"},
        {name:"Print Server",command:"printmanagement.msc",description:"Opens Print Management"},
        {name:"Spooler Status",command:"sc query Spooler",description:"Checks Print Spooler"},
        {name:"Start Spooler",command:"net start Spooler",description:"Starts Print Spooler"},
        {name:"Stop Spooler",command:"net stop Spooler",description:"Stops Print Spooler"},
        {name:"Restart Spooler",command:"net stop Spooler && net start Spooler",description:"Restarts Print Spooler"},
        {name:"Clear Print Queue",command:"net stop spooler && del /Q %systemroot%\\System32\\spool\\PRINTERS\\* && net start spooler",description:"Clears print queue"},
        {name:"Printer Drivers",command:"pnputil /enum-drivers",description:"Lists installed drivers"},
        {name:"PrintUI",command:"printui /s /t2",description:"Opens printer driver manager"},
        {name:"Add Printer",command:"rundll32 printui.dll,PrintUIEntry /il",description:"Opens Add Printer"},
        {name:"Printer Server Properties",command:"rundll32 printui.dll,PrintUIEntry /s",description:"Opens print server properties"},
        {name:"Printer Test Page",command:"rundll32 printui.dll,PrintUIEntry /k /n \"PRINTER\"",description:"Prints test page"},
        {name:"Printer Properties",command:"rundll32 printui.dll,PrintUIEntry /p /n \"PRINTER\"",description:"Opens printer properties"},
        {name:"Remove Printer",command:"rundll32 printui.dll,PrintUIEntry /dl /n \"PRINTER\"",description:"Removes printer"},
        {name:"Add Network Printer",command:"rundll32 printui.dll,PrintUIEntry /in /n \"\\\\SERVER\\PRINTER\"",description:"Adds shared printer"},
        {name:"Printer Port",command:"wmic printer get name,portname",description:"Shows printer port"},
        {name:"Printer Driver",command:"wmic printer get name,drivername",description:"Shows printer driver"},
        {name:"Printer Status",command:"wmic printer get name,printerstatus",description:"Shows printer status"},
        {name:"Printer Error",command:"wmic printer get name,printerstate",description:"Shows printer state"},
        {name:"Printer Location",command:"wmic printer get name,location",description:"Shows printer location"},
        {name:"Printer Comment",command:"wmic printer get name,comment",description:"Shows printer comment"},
        {name:"Printer Shared",command:"wmic printer get name,shared",description:"Shows shared status"},
        {name:"Printer Network",command:"wmic printer get name,network",description:"Shows network printer status"},
        {name:"Print Jobs",command:"powershell Get-PrintJob -PrinterName \"PRINTER\"",description:"Lists print jobs"},
        {name:"Remove Print Job",command:"powershell Remove-PrintJob -PrinterName \"PRINTER\" -ID 1",description:"Removes print job"},
        {name:"Pause Printer",command:"powershell Suspend-PrintJob -PrinterName \"PRINTER\" -ID 1",description:"Pauses print job"},
        {name:"Resume Printer",command:"powershell Resume-PrintJob -PrinterName \"PRINTER\" -ID 1",description:"Resumes print job"},
        {name:"Printer Configuration",command:"powershell Get-Printer",description:"Lists printer configuration"},
        {name:"Printer Driver List",command:"powershell Get-PrinterDriver",description:"Lists printer drivers"},
        {name:"Printer Port List",command:"powershell Get-PrinterPort",description:"Lists printer ports"},
        {name:"Print Processor",command:"powershell Get-PrintProcessor",description:"Lists print processors"},
        {name:"Print Service",command:"sc query Spooler",description:"Checks print service"},
        {name:"Shared Printers",command:"net view \\\\SERVER",description:"Shows server shares"},
        {name:"Printer UNC Test",command:"dir \\\\SERVER\\PRINTER",description:"Tests network printer path"},
        {name:"Printer Server Ping",command:"ping PRINTER_SERVER",description:"Tests printer server"},
        {name:"Printer Port Test",command:"powershell Test-NetConnection PRINTER_IP -Port 9100",description:"Tests RAW printing port"},
        {name:"IPP Port Test",command:"powershell Test-NetConnection PRINTER_IP -Port 631",description:"Tests IPP port"},
        {name:"LPD Port Test",command:"powershell Test-NetConnection PRINTER_IP -Port 515",description:"Tests LPD port"},
        {name:"Printer Events",command:"eventvwr.msc",description:"Checks printer event logs"},
        {name:"Print Management",command:"printmanagement.msc",description:"Manages print servers"},
        {name:"Printer Folder",command:"shell:PrintersFolder",description:"Opens printer folder"},
        {name:"Default Printer PowerShell",command:"powershell Get-CimInstance Win32_Printer | ? Default",description:"Shows default printer"},
        {name:"Printer Queue Folder",command:"explorer %systemroot%\\System32\\spool\\PRINTERS",description:"Opens spool queue folder"},
        {name:"Restart Print Service",command:"powershell Restart-Service Spooler",description:"Restarts spooler service"},
        {name:"Printer WMI",command:"wmic printer list brief",description:"Shows brief printer information"},
        {name:"Network Printer Search",command:"net view /all",description:"Lists network resources"}
    ],

    // =========================================================
    // 8. TROUBLESHOOTING - 50
    // =========================================================
    troubleshooting: [
        {name:"System File Scan",command:"sfc /scannow",description:"Repairs system files"},
        {name:"DISM Check",command:"DISM /Online /Cleanup-Image /CheckHealth",description:"Checks component store"},
        {name:"DISM Scan",command:"DISM /Online /Cleanup-Image /ScanHealth",description:"Scans component store"},
        {name:"DISM Repair",command:"DISM /Online /Cleanup-Image /RestoreHealth",description:"Repairs Windows image"},
        {name:"Check Disk",command:"chkdsk C: /scan",description:"Scans disk"},
        {name:"Event Viewer",command:"eventvwr.msc",description:"Opens event logs"},
        {name:"Reliability Monitor",command:"perfmon /rel",description:"Opens Reliability Monitor"},
        {name:"Device Manager",command:"devmgmt.msc",description:"Opens Device Manager"},
        {name:"Task Manager",command:"taskmgr",description:"Opens Task Manager"},
        {name:"Resource Monitor",command:"resmon",description:"Opens Resource Monitor"},
        {name:"Performance Monitor",command:"perfmon",description:"Opens Performance Monitor"},
        {name:"System Information",command:"msinfo32",description:"Opens system information"},
        {name:"DirectX Diagnostic",command:"dxdiag",description:"Runs DirectX diagnostics"},
        {name:"Windows Troubleshooter",command:"msdt.exe -id DeviceDiagnostic",description:"Runs hardware troubleshooter"},
        {name:"Network Troubleshooter",command:"msdt.exe /id NetworkDiagnosticsNetworkAdapter",description:"Runs network diagnostics"},
        {name:"Internet Troubleshooter",command:"msdt.exe /id NetworkDiagnosticsWeb",description:"Runs internet diagnostics"},
        {name:"Power Troubleshooter",command:"msdt.exe /id PowerDiagnostic",description:"Runs power diagnostics"},
        {name:"Audio Troubleshooter",command:"msdt.exe /id AudioPlaybackDiagnostic",description:"Runs audio diagnostics"},
        {name:"Printer Troubleshooter",command:"msdt.exe /id PrinterDiagnostic",description:"Runs printer diagnostics"},
        {name:"Windows Update Troubleshooter",command:"msdt.exe /id WindowsUpdateDiagnostic",description:"Runs update diagnostics"},
        {name:"Boot Configuration",command:"bcdedit",description:"Shows boot configuration"},
        {name:"Boot Repair Scan",command:"bootrec /scanos",description:"Scans Windows installations"},
        {name:"Boot Fix MBR",command:"bootrec /fixmbr",description:"Repairs MBR"},
        {name:"Boot Fix Boot",command:"bootrec /fixboot",description:"Repairs boot sector"},
        {name:"Boot Rebuild BCD",command:"bootrec /rebuildbcd",description:"Rebuilds boot configuration"},
        {name:"Safe Mode Configuration",command:"msconfig",description:"Opens boot configuration"},
        {name:"Startup Apps",command:"taskmgr",description:"Manage startup applications"},
        {name:"Windows Update",command:"ms-settings:windowsupdate",description:"Opens Windows Update"},
        {name:"Update History",command:"ms-settings:windowsupdate-history",description:"Shows update history"},
        {name:"Recovery Settings",command:"ms-settings:recovery",description:"Opens recovery settings"},
        {name:"Activation Settings",command:"ms-settings:activation",description:"Opens activation settings"},
        {name:"Privacy Settings",command:"ms-settings:privacy",description:"Opens privacy settings"},
        {name:"Display Settings",command:"ms-settings:display",description:"Opens display settings"},
        {name:"Sound Settings",command:"ms-settings:sound",description:"Opens sound settings"},
        {name:"Network Settings",command:"ms-settings:network",description:"Opens network settings"},
        {name:"Bluetooth Settings",command:"ms-settings:bluetooth",description:"Opens Bluetooth settings"},
        {name:"Power Settings",command:"powercfg.cpl",description:"Opens power settings"},
        {name:"Battery Report",command:"powercfg /batteryreport",description:"Creates battery report"},
        {name:"Energy Report",command:"powercfg /energy",description:"Creates energy report"},
        {name:"Sleep States",command:"powercfg /a",description:"Shows available sleep states"},
        {name:"Wake History",command:"powercfg /lastwake",description:"Shows last wake source"},
        {name:"System Boot Time",command:"wmic os get lastbootuptime",description:"Shows last boot"},
        {name:"Crash Dump Settings",command:"sysdm.cpl",description:"Opens system properties"},
        {name:"Windows Logs",command:"eventvwr.msc",description:"Opens Windows logs"},
        {name:"Blue Screen Events",command:"eventvwr.msc",description:"Checks BSOD events"},
        {name:"Application Logs",command:"eventvwr.msc",description:"Checks application logs"},
        {name:"System Logs",command:"eventvwr.msc",description:"Checks system logs"},
        {name:"Driver Verification",command:"verifier",description:"Opens Driver Verifier"},
        {name:"Memory Diagnostic",command:"mdsched.exe",description:"Runs Windows Memory Diagnostic"},
        {name:"Clean Boot",command:"msconfig",description:"Opens clean boot configuration"}
    ],

    // =========================================================
    // 9. SECURITY & FIREWALL - 50
    // =========================================================
    security: [
        {name:"Firewall Status",command:"netsh advfirewall show allprofiles",description:"Shows firewall status"},
        {name:"Current Firewall",command:"netsh advfirewall show currentprofile",description:"Shows current firewall profile"},
        {name:"Firewall Rules",command:"netsh advfirewall firewall show rule name=all",description:"Lists firewall rules"},
        {name:"Firewall ON",command:"netsh advfirewall set allprofiles state on",description:"Enables firewall"},
        {name:"Firewall OFF",command:"netsh advfirewall set allprofiles state off",description:"Disables firewall"},
        {name:"Domain Firewall ON",command:"netsh advfirewall set domainprofile state on",description:"Enables domain firewall"},
        {name:"Private Firewall ON",command:"netsh advfirewall set privateprofile state on",description:"Enables private firewall"},
        {name:"Public Firewall ON",command:"netsh advfirewall set publicprofile state on",description:"Enables public firewall"},
        {name:"Add Firewall Rule",command:"netsh advfirewall firewall add rule name=\"Test Rule\" dir=in action=allow protocol=TCP localport=8080",description:"Creates inbound rule"},
        {name:"Delete Firewall Rule",command:"netsh advfirewall firewall delete rule name=\"Test Rule\"",description:"Deletes firewall rule"},
        {name:"Block Port",command:"netsh advfirewall firewall add rule name=\"Block 8080\" dir=in action=block protocol=TCP localport=8080",description:"Blocks TCP port"},
        {name:"Allow Port",command:"netsh advfirewall firewall add rule name=\"Allow 8080\" dir=in action=allow protocol=TCP localport=8080",description:"Allows TCP port"},
        {name:"Security Center",command:"wscui.cpl",description:"Opens Windows Security"},
        {name:"Windows Security",command:"windowsdefender:",description:"Opens Windows Security"},
        {name:"Defender Status",command:"powershell Get-MpComputerStatus",description:"Shows Defender status"},
        {name:"Defender Threats",command:"powershell Get-MpThreat",description:"Shows detected threats"},
        {name:"Defender Preferences",command:"powershell Get-MpPreference",description:"Shows Defender preferences"},
        {name:"Defender Quick Scan",command:"powershell Start-MpScan -ScanType QuickScan",description:"Starts quick scan"},
        {name:"Defender Full Scan",command:"powershell Start-MpScan -ScanType FullScan",description:"Starts full scan"},
        {name:"Defender Update",command:"powershell Update-MpSignature",description:"Updates Defender signatures"},
        {name:"BitLocker Status",command:"manage-bde -status",description:"Shows BitLocker status"},
        {name:"BitLocker Drives",command:"manage-bde -status C:",description:"Shows C drive encryption"},
        {name:"TPM Status",command:"tpm.msc",description:"Opens TPM console"},
        {name:"TPM Information",command:"powershell Get-Tpm",description:"Shows TPM information"},
        {name:"Certificates User",command:"certmgr.msc",description:"Opens user certificates"},
        {name:"Certificates Computer",command:"certlm.msc",description:"Opens computer certificates"},
        {name:"Local Security Policy",command:"secpol.msc",description:"Opens security policy"},
        {name:"Group Policy",command:"gpedit.msc",description:"Opens Local Group Policy"},
        {name:"Credential Manager",command:"control /name Microsoft.CredentialManager",description:"Opens Credential Manager"},
        {name:"Audit Policy",command:"auditpol /get /category:*",description:"Shows audit policy"},
        {name:"Security Accounts",command:"secpol.msc",description:"Opens security settings"},
        {name:"Open Ports",command:"netstat -ano",description:"Shows active ports"},
        {name:"Listening Ports",command:"netstat -ano | findstr LISTENING",description:"Shows listening ports"},
        {name:"ARP Cache",command:"arp -a",description:"Shows ARP entries"},
        {name:"Logged User",command:"whoami /all",description:"Shows complete identity"},
        {name:"User SID",command:"whoami /user",description:"Shows SID"},
        {name:"Group SID",command:"whoami /groups",description:"Shows group SIDs"},
        {name:"Privileges",command:"whoami /priv",description:"Shows privileges"},
        {name:"Kerberos Tickets",command:"klist",description:"Shows Kerberos tickets"},
        {name:"Purge Tickets",command:"klist purge",description:"Clears Kerberos tickets"},
        {name:"Secure Channel",command:"nltest /sc_verify:DOMAIN.LOCAL",description:"Checks domain secure channel"},
        {name:"UAC Settings",command:"UserAccountControlSettings",description:"Opens UAC settings"},
        {name:"Firewall GUI",command:"wf.msc",description:"Opens advanced firewall"},
        {name:"Windows Security Settings",command:"ms-settings:windowsdefender",description:"Opens Windows Security settings"},
        {name:"Privacy Settings",command:"ms-settings:privacy",description:"Opens privacy controls"},
        {name:"Account Protection",command:"ms-settings:signinoptions",description:"Opens sign-in options"},
        {name:"Device Security",command:"ms-settings:windowsdefender",description:"Opens device security"},
        {name:"Credential Guard Check",command:"msinfo32",description:"Checks security features"},
        {name:"Secure Boot Check",command:"powershell Confirm-SecureBootUEFI",description:"Checks Secure Boot"},
        {name:"System Protection",command:"sysdm.cpl",description:"Opens system protection settings"}
    ],

    // =========================================================
    // 10. WINDOWS / ADMIN TOOLS - 50
    // =========================================================
    windowsTools: [
        {name:"Run Dialog",command:"Win + R",description:"Opens Run dialog"},
        {name:"Command Prompt",command:"cmd",description:"Opens Command Prompt"},
        {name:"PowerShell",command:"powershell",description:"Opens PowerShell"},
        {name:"Windows Terminal",command:"wt",description:"Opens Windows Terminal"},
        {name:"Registry Editor",command:"regedit",description:"Opens Registry Editor"},
        {name:"Group Policy Editor",command:"gpedit.msc",description:"Opens Local Group Policy"},
        {name:"Registry Console",command:"regedt32",description:"Opens Registry Editor"},
        {name:"Services",command:"services.msc",description:"Opens Services"},
        {name:"Event Viewer",command:"eventvwr.msc",description:"Opens Event Viewer"},
        {name:"Task Scheduler",command:"taskschd.msc",description:"Opens Task Scheduler"},
        {name:"Computer Management",command:"compmgmt.msc",description:"Opens Computer Management"},
        {name:"Device Manager",command:"devmgmt.msc",description:"Opens Device Manager"},
        {name:"Disk Management",command:"diskmgmt.msc",description:"Opens Disk Management"},
        {name:"Print Management",command:"printmanagement.msc",description:"Opens Print Management"},
        {name:"Local Users",command:"lusrmgr.msc",description:"Opens Local Users"},
        {name:"System Properties",command:"sysdm.cpl",description:"Opens System Properties"},
        {name:"Network Connections",command:"ncpa.cpl",description:"Opens network adapters"},
        {name:"Programs",command:"appwiz.cpl",description:"Opens Programs and Features"},
        {name:"Firewall",command:"firewall.cpl",description:"Opens firewall settings"},
        {name:"Internet Options",command:"inetcpl.cpl",description:"Opens Internet Options"},
        {name:"Mouse Properties",command:"main.cpl",description:"Opens mouse properties"},
        {name:"Keyboard Properties",command:"control keyboard",description:"Opens keyboard settings"},
        {name:"Sound",command:"mmsys.cpl",description:"Opens sound settings"},
        {name:"Power Options",command:"powercfg.cpl",description:"Opens power options"},
        {name:"Date Time",command:"timedate.cpl",description:"Opens date/time settings"},
        {name:"Region",command:"intl.cpl",description:"Opens regional settings"},
        {name:"Fonts",command:"control fonts",description:"Opens fonts folder"},
        {name:"System Info",command:"msinfo32",description:"Opens system information"},
        {name:"DirectX",command:"dxdiag",description:"Opens DirectX Diagnostic"},
        {name:"Character Map",command:"charmap",description:"Opens Character Map"},
        {name:"Calculator",command:"calc",description:"Opens Calculator"},
        {name:"Notepad",command:"notepad",description:"Opens Notepad"},
        {name:"Paint",command:"mspaint",description:"Opens Paint"},
        {name:"WordPad",command:"write",description:"Opens WordPad if available"},
        {name:"File Explorer",command:"explorer",description:"Opens File Explorer"},
        {name:"This PC",command:"explorer shell:MyComputerFolder",description:"Opens This PC"},
        {name:"Control Panel",command:"control",description:"Opens Control Panel"},
        {name:"Settings",command:"start ms-settings:",description:"Opens Windows Settings"},
        {name:"Windows Update",command:"start ms-settings:windowsupdate",description:"Opens Windows Update"},
        {name:"Bluetooth",command:"start ms-settings:bluetooth",description:"Opens Bluetooth settings"},
        {name:"WiFi Settings",command:"start ms-settings:network-wifi",description:"Opens Wi-Fi settings"},
        {name:"Display Settings",command:"start ms-settings:display",description:"Opens display settings"},
        {name:"Apps Settings",command:"start ms-settings:appsfeatures",description:"Opens installed apps"},
        {name:"Accounts Settings",command:"start ms-settings:accounts",description:"Opens account settings"},
        {name:"Backup Settings",command:"start ms-settings:backup",description:"Opens backup settings"},
        {name:"Recovery Settings",command:"start ms-settings:recovery",description:"Opens recovery settings"},
        {name:"Storage Settings",command:"start ms-settings:storagesense",description:"Opens storage settings"},
        {name:"Remote Desktop",command:"mstsc",description:"Opens Remote Desktop"},
        {name:"Remote Desktop Computer",command:"mstsc /v:SERVER",description:"Connects to RDP server"},
        {name:"Remote Desktop Admin",command:"mstsc /admin /v:SERVER",description:"Connects to RDP admin session"},
        {name:"Shutdown",command:"shutdown /s /t 0",description:"Shuts down computer"},
        {name:"Restart",command:"shutdown /r /t 0",description:"Restarts computer"}
    ]
};


// =========================================================
// HELPER FUNCTIONS
// =========================================================

function getAllCommands() {
    return Object.values(commandCategories).flat();
}

function getCommandsByCategory(category) {
    return commandCategories[category] || [];
}

function searchCommands(keyword) {
    const search = keyword.toLowerCase().trim();

    if (!search) {
        return getAllCommands();
    }

    return getAllCommands().filter(item =>
        item.name.toLowerCase().includes(search) ||
        item.command.toLowerCase().includes(search) ||
        item.description.toLowerCase().includes(search)
    );
}

function getCommandCount() {
    return getAllCommands().length;
}


// =========================================================
// CATEGORY NAMES
// =========================================================

const categoryNames = {
    systemInfo: "System Information",
    networking: "Networking",
    users: "Users & Accounts",
    services: "Services & Processes",
    activeDirectory: "Active Directory",
    storage: "Disk & Storage",
    printers: "Printers",
    troubleshooting: "Troubleshooting",
    security: "Security & Firewall",
    windowsTools: "Windows / Admin Tools"
};


// =========================================================
// TOOLKIT INFORMATION
// =========================================================

console.log("======================================");
console.log("      IT SUPPORT TOOLKIT LOADED");
console.log("======================================");

console.log("Total Commands:", getCommandCount());

Object.keys(commandCategories).forEach(category => {
    console.log(
        categoryNames[category],
        ":",
        commandCategories[category].length
    );
});
